title: Shuozhang's Homepage
page-top-title: Shuozhang
top-section-bg-text: Electrical Engineering 
home-subtitle: 单板硬件开发&ensp;|&ensp;张硕
copyright-text: '&copy; Shuozhang 2023-2025. All Rights Reserved.'
